{{- $role := "apigee-cassandra-guardrails" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $role }}
  namespace: {{ include "namespace" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $role }}
subjects:
- kind: ServiceAccount
  name: {{ $role }}-sa
  namespace: {{ include "namespace" . }}
