{{- if not .Values.gcp.workloadIdentity.enabled  -}}
{{- if and .Values.metrics.enabled (not .Values.metrics.serviceAccountRef) (not .Values.serviceAccountSecretProviderClass) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metricsGSAName" . }}
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{- $c :=  include "tryFileContent.get" (dict "files" .Files "f" (required ".metrics.serviceAccountPath is required!!" .Values.metrics.serviceAccountPath)) }}
    {{- $c | b64enc | nindent 4 }}
---
{{- end -}}
{{- end }}