apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigeehybrid
  namespace: argocd
  annotations:
   notifications.argoproj.io/subscribe.on-deployed.slack: hybridupdates  #Slack Channel name  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:AyoSal/argocd-hybrid.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: apigee
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2    
    syncOptions:
    - CreateNamespace=true
