{{- $name := "default" }}
{{- $redisName := "apigee-redis" -}}
{{- if not .Values.redis.auth.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $redisName }}-{{ $name }}-creds"
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  redis.auth.password: "{{ b64enc .Values.redis.auth.password }}"
{{- end -}}