apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apigee-cassandra-backup
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "patch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotclasses"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["list"]