apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apigee-ingressgateway-sds
  namespace: {{ .Values.namespace }}
  labels:
    apigee.cloud.google.com/platform: apigee
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apigee-ingressgateway-sds
subjects:
- kind: ServiceAccount
  name: apigee-ingressgateway
  namespace: {{ .Values.namespace }}