apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apigee-ingressgateway-sds
  namespace: {{ .Values.namespace }}
  labels:
    apigee.cloud.google.com/platform: apigee
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list