apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apigee-ingressgateway-manager
  namespace: {{ .Values.namespace }}
  labels:
    apigee.cloud.google.com/platform: apigee
subjects:
- kind: ServiceAccount
  name: apigee-ingressgateway-manager
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: apigee-ingressgateway-manager
  apiGroup: rbac.authorization.k8s.io
