apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apigee-istiod
  namespace: {{ include "namespace" . }}
  labels:
    apigee.cloud.google.com/platform: apigee
spec:
  commonName: apigee-ingressgateway-manager.{{ include "namespace" . }}.svc
  dnsNames:
  - "apigee-ingressgateway-manager.{{ include "namespace" . }}.svc"
  duration: 48h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: apigee-ingress-manager-ca-issuer
  renewBefore: 24h0m0s
  secretName: apigee-istiod-cert
