apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-datastore
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
    notifications.argoproj.io/subscribe.on-deployed.slack: hybridupdates
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/apigee-charts/apigee-datastore
    repoURL: 'git@github.com:AyoSal/argocd-hybrid.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-ds.yaml
  destination:
    namespace: apigee
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2    
      prune: true
    syncOptions:
      - CreateNamespace=true
