apiVersion: argoproj.io/v1alpha1
  #test  
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: nginx
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: HEAD
  destination:
    namespace: apigee
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
