apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store-csi-driver
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: hybridupdates
    argocd.argoproj.io/sync-wave: "7"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: ''
    repoURL: 'https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts'
    chart: secrets-store-csi-driver  
    targetRevision: v1.3.4
    helm:
      parameters:
        - name: syncSecret.enabled
          value: 'true'
        - name: enableSecretRotation
          value: 'true'
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
