apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtualhost
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/apigee-charts/apigee-virtualhost
    repoURL: 'git@github.com:AyoSal/argocd-hybrid.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-vhost.yaml
  destination:
    namespace: apigee
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
