#Override Values for Apigee Environment 2 |Hybrid 1.10.3 on GKE Cluster deployed with ArgoCD and Helm

gcp:
  region: us-east1
  projectID: ayos-os-test

k8sCluster:
  name: argocd-1103
  region: us-east4 # Must be the closest Google Cloud region to your cluster.
org: ayos-os-test
orgscopedUDCA: true
instanceID: "argocd-helm1102"

imagePullSecrets:
  - name: gcr-cred

nodeSelector:
 # This flag determines if the scheduling passes/fails if the labels are missing.
 requiredForScheduling: true
 apigeeRuntime:
   key: "cloud.google.com/gke-nodepool"
   value: "apigee-runtime"
 apigeeData:
   key: "cloud.google.com/gke-nodepool"
   value: "apigee-data"

hub: gcr.io/apigee-release/hybrid
envs:
- name: argocd-env2
  serviceAccountSecretRefs:
    synchronizer: "hybrid-secret-for-serviceaccount"
    udca: "hybrid-secret-for-serviceaccount"
    runtime: "hybrid-secret-for-serviceaccount"


synchronizer:
  replicaCountMin: '1'
  replicaCountMax: '2'
 
runtime:
  replicaCountMin: '1'
  replicaCountMax: '2'

udca:
  serviceAccountRef: "hybrid-secret-for-serviceaccount"
  hostNetwork: true

