apiVersion: v1
kind: Service
metadata:
  labels:
    app: apigee-ingressgateway-manager
    apigee.cloud.google.com/platform: apigee
  name: apigee-ingressgateway-manager
  namespace: {{ include "namespace" . }}
spec:
  ports:
  - name: grpc-xds
    port: 15010
    protocol: TCP
    targetPort: 15010
  - name: https-dns
    port: 15012
    protocol: TCP
    targetPort: 15012
  - name: https-webhook
    port: 443
    protocol: TCP
    targetPort: 15017
  - name: http-monitoring
    port: 15014
    protocol: TCP
    targetPort: 15014
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 15053
  - name: dns-tls
    port: 853
    protocol: TCP
    targetPort: 15053
  selector:
    app: apigee-ingressgateway-manager
  type: ClusterIP
