apiVersion: v1
kind: Service
metadata:
  name: ingress-service
  namespace: apigee
spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: apigee-ingressgateway #required
    ingress_name: argocd-ingress
    org: ayos-os-test
  type: LoadBalancer
