{{- $runtimeName := "apigee-runtime" -}}
{{- $values := .Values -}}
{{- $chart := .Chart -}}
{{- $files := .Files -}}
{{- $release := .Release -}}
{{- range $i, $env := .Values.envs -}}
{{- if eq $env.name  $values.env -}}
{{- $generatedName := include "envScopeEncodedName" (dict "org" $values.org "env" $env.name) -}}
{{- if $values.org -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $generatedName }}-encryption-keys"
  namespace: {{ include "namespace"  (dict "release" $release "values" $values) }}
type: Opaque
data:
  kmsEncryptionKey: |-
  {{- if $values.kmsEncryptionPath }}
  {{ $files.Get $values.kmsEncryptionPath | b64enc | nindent 4 }}
  {{- else if $values.kmsEncryptionKey -}}
  {{ include "validateEncryptionKey" (dict "key" $values.kmsEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- else -}}
  {{ include "validateEncryptionKey" (dict "key" $values.defaults.org.kmsEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- end }}
  cacheEncryptionKey: |-
  {{- if $env.cacheEncryptionPath -}}
  {{ $files.Get $env.cacheEncryptionPath | b64enc | nindent 4 }}
  {{- else if $env.cacheEncryptionKey -}}
  {{ include "validateEncryptionKey" (dict "key" $env.cacheEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- else -}}
  {{ include "validateEncryptionKey" (dict "key" $values.defaults.env.kmsEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- end }}
  kvmEncryptionKey: |-
  {{- if $values.kvmEncryptionPath -}}
  {{ $files.Get $values.kvmEncryptionPath | b64enc | nindent 4 }}
  {{- else if $values.kvmEncryptionKey -}}
  {{ include "validateEncryptionKey" (dict "key" $values.kvmEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- else -}}
  {{ include "validateEncryptionKey" (dict "key" $values.defaults.org.kvmEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- end }}
  envKvmEncryptionKey: |-
  {{- if $env.kvmEncryptionPath -}}
  {{ $files.Get $env.kvmEncryptionPath | b64enc | nindent 4 }}
  {{- else if $env.kvmEncryptionKey -}}
  {{/* KVM encryption key with env scope.*/}}
  {{ include "validateEncryptionKey" (dict "key" $env.kvmEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- else -}}
  {{ include "validateEncryptionKey" (dict "key" $values.defaults.env.kvmEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}