{{- $runtimeName := "apigee-runtime" -}}
{{- $values := .Values -}}
{{- $chart := .Chart -}}
{{- $files := .Files -}}
{{- $release := .Release -}}
{{- range $i, $env := .Values.envs -}}
{{- if eq $env.name  $values.env -}}
{{- $generatedName := include "envScopeEncodedName" (dict "org" $values.org "env" $env.name) -}}
{{- if $values.org -}}
{{- if not $values.gcp.workloadIdentity.enabled }}
{{- if not (and $env.serviceAccountSecretRefs $env.serviceAccountSecretRefs.runtime) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $runtimeName }}-{{ $generatedName }}-svc-account"
  namespace: {{ include "namespace"  (dict "release" $release "values" $values) }}
type: Opaque
data:
  client_secret.json: |
    {{ $files.Get ( required "$env.serviceAccountPaths.runtime is required!!" $env.serviceAccountPaths.runtime) | b64enc | nindent 4 }}
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}