{{- $actionbk := "apigee-cassandra-backup"}}
{{- $secretKey := "dbbackup_key.json" }}
{{- if .Values.cassandra.backup.enabled }}
{{- if not .Values.cassandra.backup.serviceAccountRef }}
{{- if .Values.cassandra.backup.serviceAccountPath }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $actionbk }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  {{ $secretKey }}: |
    {{ .Files.Get ( required ".Values.cassandra.backup.serviceAccountPath is required!!"  .Values.cassandra.backup.serviceAccountPath) | b64enc | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}