{{- if .Values.cassandra.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigee-cassandra-backup-sa
  namespace: {{ include "namespace" . }}
  {{- if .Values.gcp.workloadIdentity.enabled }}
  annotations:
    iam.gke.io/gcp-service-account: {{ default .Values.gcp.workloadIdentity.gsa .Values.cassandra.backup.gsa }}
  {{- end }}
{{- end }}
