{{- $name := "default" }}
{{- if not (or .Values.cassandra.auth.secret .Values.cassandra.auth.secretProviderClass )}}
apiVersion: v1
kind: Secret
metadata:
  name: apigee-datastore-{{ $name }}-creds
  namespace: {{ include "namespace" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  default.password: "{{ b64enc .Values.cassandra.auth.default.password }}"
  admin.user: "{{ b64enc .Values.cassandra.auth.admin.username }}"
  admin.password: "{{ b64enc .Values.cassandra.auth.admin.password }}"
  dml.user: "{{ b64enc .Values.cassandra.auth.dml.username }}"
  dml.password: "{{ b64enc .Values.cassandra.auth.dml.password }}"
  ddl.user: "{{ b64enc .Values.cassandra.auth.ddl.username }}"
  ddl.password: "{{ b64enc .Values.cassandra.auth.ddl.password }}"
  jmx.user: "{{ b64enc .Values.cassandra.auth.jmx.username }}"
  jmx.password: "{{ b64enc .Values.cassandra.auth.jmx.password }}"
  jolokia.user: "{{ b64enc .Values.cassandra.auth.jolokia.username }}"
  jolokia.password: "{{ b64enc .Values.cassandra.auth.jolokia.password }}"
{{- end }}