{{- $actionrs := "apigee-cassandra-restore"}}
{{- $secretKey := "dbbackup_key.json" }}
{{- if .Values.cassandra.restore.enabled }}
{{- if or (.Values.cassandra.restore.serviceAccountPath) (.Values.cassandra.backup.serviceAccountPath) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $actionrs }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  {{ $secretKey }}: |
    {{- if .Values.cassandra.restore.serviceAccountPath }}
    {{ .Files.Get ( required "cassandra.restore.serviceAccountPath is required!!"  .Values.cassandra.restore.serviceAccountPath) | b64enc | nindent 4 }}
    {{- else if .Values.cassandra.backup.serviceAccountPath }}
    {{ .Files.Get ( required "cassandra.backup.serviceAccountPath is required!!"  .Values.cassandra.backup.serviceAccountPath) | b64enc | nindent 4 }}
    {{- end }}
---
{{- end }}
{{- end }}