{{- $metricsName := "apigee-metrics" -}}
{{- if not .Values.gcp.workloadIdentity.enabled  -}}
{{- if and .Values.metrics.enabled (not .Values.metrics.serviceAccountRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $metricsName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{ .Files.Get ( required ".metrics.serviceAccountPath is required!!" .Values.metrics.serviceAccountPath) | b64enc | nindent 4 }}
---
{{- end -}}
{{- end }}