{{- $fluentdLoggerName := "apigee-logger" -}}
{{- if not .Values.gcp.workloadIdentity.enabled  -}}
{{- if and .Values.logger.enabled (not .Values.logger.serviceAccountRef) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fluentdLoggerName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{ .Files.Get ( required ".logger.serviceAccountPath is required!!" .Values.logger.serviceAccountPath) | b64enc | nindent 4 }}
{{- end }}
{{- end }}