{{- if not .Values.axHashSaltSecret }}
{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $generatedName }}-ax-salt
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  salt: {{ default .Values.defaults.org.axHashSalt .Values.axHashSalt | b64enc }}
{{- end }}