{{- if and (not .Values.gcp.workloadIdentity.enabled) (not .Values.connectAgent.serviceAccountRef) }}
{{- $connectAgentName := "apigee-connect-agent" -}}
{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $connectAgentName }}-{{ $generatedName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{ .Files.Get ( required "connectAgent.serviceAccountPath is required!!"  .Values.connectAgent.serviceAccountPath) | b64enc | nindent 4 }}
---
{{- end }}