{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $generatedName }}-data-encryption"
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  plainTextDEK: {{ .Values.defaults.org.contractEncryptionKey }}