{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $generatedName }}-encryption-keys"
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  kmsEncryptionKey: |-
  {{- if .Values.kmsEncryptionPath -}}
  {{ .Files.Get .Values.kmsEncryptionPath | b64enc | nindent 4 }}
  {{- else if .Values.kmsEncryptionKey -}}
  {{ include "validateEncryptionKey" (dict "key" .Values.kmsEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- else -}}
  {{ include "validateEncryptionKey" (dict "key" .Values.defaults.org.kmsEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- end }}
  kvmEncryptionKey: |-
  {{- if .Values.kvmEncryptionPath -}}
  {{ .Files.Get .Values.kvmEncryptionPath | b64enc | nindent 4 }}
  {{- else if .Values.kvmEncryptionKey -}}
  {{ include "validateEncryptionKey" (dict "key" .Values.kvmEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- else -}}
  {{ include "validateEncryptionKey" (dict "key" .Values.defaults.org.kvmEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- end }}
