{{- if and (not .Values.gcp.workloadIdentity.enabled) (not .Values.mart.serviceAccountRef) }}
{{- $martName := "apigee-mart" -}}
{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $martName }}-{{ $generatedName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{ .Files.Get ( required "mart.serviceAccountPath is required!!" .Values.mart.serviceAccountPath) | b64enc | nindent 4 }}
---
{{- end }}