{{- if .Values.org }}
{{- $values := .Values -}}
{{- $files := .Files -}}
{{- $release := .Release -}}
{{- range $index, $vh := $values.virtualhosts }}
{{- if eq $vh.name (required "given $vh.name is not part of virtualhosts in the overrides yaml" $values.envgroup) -}}
{{- $certName := printf "%s-%s" $values.org $vh.name }}
{{- if and (not $vh.sslSecret) (and $vh.sslCertPath $vh.sslKeyPath $vh.caCertPath) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $certName }}-cacert"
  namespace: {{ include "namespace"  (dict "release" $release "values" $values) }}
type: Opaque
data:
  cacert: |-
    {{ $files.Get ( required "$vh.caCertPath is required!!"  $vh.caCertPath) | b64enc | nindent 4 }}
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
