{{- if .Values.org }}
{{- $values := .Values -}}
{{- $files := .Files -}}
{{- $release := .Release -}}
{{- range $index, $vh := $values.virtualhosts }}
{{- if eq $vh.name (required "given $vh.name is not part of virtualhosts in the overrides yaml" $values.envgroup) -}}
{{- $certName := printf "%s-%s" $values.org $vh.name }}
{{- if and (not $vh.sslSecret) (and $vh.sslCertPath $vh.sslKeyPath) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $certName }}"
  namespace: {{ include "namespace"  (dict "release" $release "values" $values) }}
type: Opaque
data:
  cert: |-
    {{ $files.Get (required "$vh.sslCertPath is required!!"  $vh.sslCertPath) | b64enc | nindent 4 }}
  key: |-
    {{ $files.Get (required "$vh.sslKeyPath is required!!"  $vh.sslKeyPath) | b64enc | nindent 4 }}
  {{- with $vh.caCertPath }}
  cacert: |-
    {{ $files.Get (required "$vh.caCertPath is required!!"  $vh.caCertPath) | b64enc | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
