{{- if .Values.mintTaskScheduler.serviceAccountPath -}}
{{- $mintTaskSchedulerName := "apigee-mint-task-scheduler" -}}
{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $mintTaskSchedulerName }}-{{ $generatedName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{ include "tryFileContent.get" (dict "files" $.Files "f" .Values.mintTaskScheduler.serviceAccountPath) | b64enc | nindent 4 }}
{{- end }}